// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char GPRS_APN[]      = SECRET_APN;
const char PINNUMBER[]     = SECRET_PIN;
const char GPRS_LOGIN[]    = SECRET_USERNAME;
const char GPRS_PASSWORD[] = SECRET_PASSWORD;


float co;
float co2;
float no2;
float pm25;
float voc;

void initProperties(){

  ArduinoCloud.addProperty(co, READ, 20 * SECONDS, NULL);
  ArduinoCloud.addProperty(co2, READ, 20 * SECONDS, NULL);
  ArduinoCloud.addProperty(no2, READ, 20 * SECONDS, NULL);
  ArduinoCloud.addProperty(pm25, READ, 20 * SECONDS, NULL);
  ArduinoCloud.addProperty(voc, READ, 20 * SECONDS, NULL);

}

GSMConnectionHandler ArduinoIoTPreferredConnection(PINNUMBER, GPRS_APN, GPRS_LOGIN, GPRS_PASSWORD);